ansible:
  image: python:3.9-slim
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  before_script:
    - chmod 0755 .  # HACK: https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
    - apt-get update && apt-get install -y bash git
    - ./scripts/setup.sh
  script:
    - ./scripts/lint.sh
