- hosts: local
  connection: local
  tasks:
    - ping:
    - include_vars:
        file: vars.yml
    - import_tasks: tasks/common.yml
    - import_tasks: tasks/config.yml
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/private.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/gnome.yml
