- hosts: local
  connection: local
  tasks:
    - name: Include extra metadata
      include_vars:
        file: vars.yml

    # HACK: So variables can be loaded by hostname, rather than `local`
    - name: Load custom variables
      include_vars:
        file: host_vars/{{ ansible_hostname }}.yml
      failed_when: false

    - import_tasks: tasks/user.yml
    - import_tasks: tasks/packages.yml

    - include_role:
        name: geerlingguy.ntp

    - import_tasks: tasks/boot.yml
    - import_tasks: tasks/i3.yml

    # Don't bother configuring KDE for root, just assume it's for me
    - import_tasks: tasks/kde.yml
      become: true
      become_user: "{{ user }}"

    - import_tasks: tasks/network.yml
    - import_tasks: tasks/shell.yml
    - import_tasks: tasks/input.yml
    - import_tasks: tasks/autostart.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/security.yml

    - import_tasks: tasks/python.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/intersect.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/gnome.yml
    - import_tasks: tasks/javascript.yml
    - import_tasks: tasks/applications.yml
    - import_tasks: tasks/dev.yml
    - import_tasks: tasks/media.yml

    - import_tasks: tasks/torchbox.yml
      when: is_torchbox

    - import_tasks: tasks/mac.yml
      when: "'Mac' in ansible_facts.product_name"

    - import_tasks: tasks/cleanup.yml
