- hosts: local
  connection: local
  tasks:
    - ping:
    - include_vars:
        file: vars.yml
    - import_tasks: tasks/yaourt.yml
    - import_tasks: tasks/common.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/config.yml
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/private.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/gnome.yml
    - import_tasks: tasks/i3.yml
    - import_tasks: tasks/services.yml
    - import_tasks: tasks/shell.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/autostart.yml

    - import_tasks: tasks/dabapps.yml
      when: ansible_fqdn == "TOO-Work"
    - import_tasks: tasks/laptop.yml
      when: ansible_fqdn == "TOO-Laptop"
