#!/usr/bin/env python3

import os
from scripts.install_dotfiles import *

EXEC_ORDER = [
    update,
    apt_upgrade,
    apt_install_core,
    add_apt_keys,
    add_apt_sources,
    add_apt_repos,
    update,
    apt_install_extras,
    run_custom_installs,
    install_atom_packages,
    export_atom_config,
    install_configs
]


if __name__ == '__main__':
    if os.geteuid() != 0:
        print("Please run as root!")
    elif input("Are you sure you want to install (allthethings)? [Y/N]: ").lower() == 'y':
        for script in EXEC_ORDER:
            script()
            print("\n>>{} Executed.\n".format(script.__name__))
