#!/usr/bin/env python3

import os, time
from scripts.install_dotfiles import *

EXEC_ORDER = [
    update,
    apt_upgrade,
    apt_install_core,
    add_apt_keys,
    add_apt_sources,
    add_apt_repos,
    update,
    run_custom_installs,
    update,
    apt_install_extras,
    source,
    install_atom_packages,
    export_atom_config,
    install_configs
]


if __name__ == '__main__':
    t0 = time.time()
    for script in EXEC_ORDER:
        script()
        print("\n>> {} Exescuted.\n".format(script.__name__))
    t1 = time.time()
    print("Execution Complete")
    print("Took {} seconds.".format(int(t1 - t0)))
