#!/usr/bin/env python3

import os, time
from scripts.install_dotfiles import *

EXEC_ORDER = [
    update,
    apt_upgrade,
    apt_install_core,
    add_apt_keys,
    add_apt_sources,
    add_apt_repos,
    update,
    run_custom_installs,
    update,
    apt_install_extras,
    source,
    install_atom_packages,
    export_atom_config,
    install_configs
]


if __name__ == '__main__':
    t0 = "temp_time"
    if os.geteuid() != 0:
        print("Please run as root!")
    elif input("Are you sure you want to install (allthethings)? [Y/N]: ").lower() == 'y':
        t0 = time.time()
        for script in EXEC_ORDER:
            script()
            print("\n>> {} Exe1cuted.\n".format(script.__name__))
        t1 = time.time()
    print("Execution Complete")
    print("Took {} seconds.".format(t1 - t0))
