- name: Install Virtualbox dependencies
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - virtualbox-host-modules-arch

- name: Install general applications
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - bleachbit
    - clamtk
    - filezilla
    - firefox
    - gimp
    - ghostwriter
    - glogg
    - gparted
    - hplip
    - inkscape
    - kdenlive
    - kodi
    - libreoffice-fresh
    - libreoffice-fresh-en-gb
    - minecraft
    - obs-studio
    - slack-desktop
    - steam
    - thunderbird
    - tor-browser
    - virtualbox
    - vlc
    - xsane
