- name: "Install Virtualbox dependencies"
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  loop:
    - 'virtualbox-host-modules-arch'
    - 'virtualbox-guest-modules-arch'

- name: "Install general applications"
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  loop:
    - 'bleachbit'
    - 'brave-bin'
    - 'clamtk'
    - 'etcher'
    - 'filezilla'
    - 'firefox'
    - 'gimp'
    - 'ghostwriter'
    - 'glogg'
    - 'google-earth-pro'
    - 'gparted'
    - 'hplip'
    - 'inkscape'
    - 'kdenlive'
    - 'kodi'
    - libreoffice-fresh
    - libreoffice-fresh-en-gb
    - 'minecraft'
    - 'obs-studio'
    - 'slack-desktop'
    - 'steam'
    - 'thunderbird'
    - 'tor-browser'
    - 'virtualbox'
    - 'vlc'
    - 'xsane'
