- file:
    src: "/etc/xdg/autostart/{{ item }}.desktop"
    dest: "{{ home }}/.config/autostart/{{ item }}.desktop"
    mode: 0644
    owner: "{{ user }}"
    state: link
    force: true
  with_items:
    - 'pulseaudio'
    - 'org.gnome.SettingsDaemon.XSettings'
    - 'org.gnome.SettingsDaemon.DiskUtilityNotify'
    - 'org.gnome.SettingsDaemon.Keyboard'
    - 'gsettings-data-convert'
    - 'nm-applet'
    - 'lxqt-policykit-agent'
    - 'solaar'
