- name: Create autostart directory
  file:
    path: "{{ home }}/.config/autostart"
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: Autostart solaar
  file:
    src: /usr/share/applications/solaar.desktop
    dest: "{{ home }}/.config/autostart/solaar.desktop"
    state: link
    mode: 0644
    owner: "{{ user }}"
