- name: "Install autostart-related packages"
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  with_items:
    - 'dex'

- name: "Autostart services"
  file:
    src: "/etc/xdg/autostart/{{ item }}.desktop"
    dest: "{{ home }}/.config/autostart/{{ item }}.desktop"
    mode: 0644
    owner: "{{ user }}"
    state: link
    force: true
  with_items:
    - 'pulseaudio'
    - 'org.gnome.SettingsDaemon.XSettings'
    - 'org.gnome.SettingsDaemon.DiskUtilityNotify'
    - 'org.gnome.SettingsDaemon.Keyboard'
    - 'gsettings-data-convert'
    - 'nm-applet'
    - 'lxqt-policykit-agent'
    - 'solaar'

- name: "Autostart applications"
  file:
    src: "/usr/share/applications/{{ item }}.desktop"
    dest: "{{ home }}/.config/autostart/{{ item }}.desktop"
    mode: 0644
    owner: "{{ user }}"
    state: link
    force: true
  with_items:
    - 'flameshot'
    - 'libinput-gestures'
    - 'opensnitch_ui'
