- name: Create autostart directory
  file:
    path: "{{ home }}/.config/autostart"
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: Autostart solaar
  get_url:
    url: https://raw.githubusercontent.com/pwr-Solaar/Solaar/master/share/autostart/solaar.desktop
    dest: "{{ home }}/.config/autostart/solaar.desktop"
    mode: 0755
    force: true
    owner: "{{ user }}"
