- name: "Install autostart-related packages"
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  loop:
    - 'dex'

- name: "Create autostart directory"
  file:
    path: '{{ home }}/.config/autostart'
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: "Autostart services"
  file:
    src: "/etc/xdg/autostart/{{ item }}.desktop"
    dest: "{{ home }}/.config/autostart/{{ item }}.desktop"
    mode: 0644
    owner: "{{ user }}"
    state: link
    force: true
  loop:
    - 'pulseaudio'
    - 'nm-applet'
    - 'lxqt-policykit-agent'
    - 'solaar'

- name: "Autostart applications"
  file:
    src: "/usr/share/applications/{{ item }}.desktop"
    dest: "{{ home }}/.config/autostart/{{ item }}.desktop"
    mode: 0644
    owner: "{{ user }}"
    state: link
    force: true
  loop:
    - 'flameshot'
    - 'libinput-gestures'
