- name: "Install Grub"
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  with_items:
    - 'grub-customizer'
    - 'grub2-theme-archlinux'
    - 'lightdm'
    - 'lightdm-slick-greeter'
    - 'os-prober'

- name: "Enable lightdm"
  systemd:
    name: "lightdm"
    enabled: true

- name: "Disable PC Speaker"
  modprobe:
    name: pcspkr
    state: absent
  ignore_errors: true

- name: Enable Slick greeter for lightdm
  ini_file:
    path: /etc/lightdm/lightdm.conf
    section: "Seat:*"
    option: greeter-session
    value: lightdm-slick-greeter
    mode: 0644

- name: "Install file system helpers"
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  with_items:
    - dosfstools
    - exfat-utils
    - hfsprogs
    - ntfs-3g
