- name: Install Grub
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - grub-customizer
    - grub2-theme-archlinux
    - lightdm
    - lightdm-gtk-greeter
    - os-prober

- name: Enable lightdm
  systemd:
    name: lightdm
    enabled: true

- name: Disable PC Speaker
  modprobe:
    name: pcspkr
    state: absent
  ignore_errors: true

- name: Enable Slick greeter for lightdm
  ini_file:
    path: /etc/lightdm/lightdm.conf
    section: Seat:*
    option: greeter-session
    value: lightdm-gtk-greeter
    mode: 0644

- name: Set LightDM settings
  ini_file:
    path: /etc/lightdm/lightdm-gtk-greeter.conf
    section: greeter
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    mode: 0644
  loop_control:
    label: "{{ item.key }}"
  loop:
    - {key: background, value: /usr/share/backgrounds/gnome/adwaita-night.jpg}
    - {key: theme-name, value: Matcha-dark-aliz}
    - {key: icon-theme-name, value: Numix-Square}
    - {key: hide-user-image, value: "true"}
    - {key: clock-format, value: "%H:%M:%S"}

- name: Install file system helpers
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - dosfstools
    - exfat-utils
    - hfsprogs
    - ntfs-3g

- name: Install Microcode
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - amd-ucode
    - intel-ucode

- name: Install nohang
  aur:
    skip_installed: true
    name: "nohang-git"
  become: true
  become_user: aur_builder

- name: Enable nohang
  systemd:
    name: nohang-desktop
    enabled: true
