- user:
    name: "{{ user }}"
    home: "{{ home }}"
    comment: Jake Howard
    shell: '/usr/bin/zsh'
    uid: 1000
    system: true
    groups:
      - input
      - users
      - video
      - wheel
- file:
    state: directory
    path: '{{ home }}/Projects'
    owner: "{{ user }}"
- file:
    state: directory
    path: '/opt/pyenv'
    owner: "{{ user }}"
    group: users

- modprobe:
    name: pcspkr
    state: absent
