- copy:
    src: ./files/libinput-gestures.conf
    dest: /etc/libinput-gestures.conf
    mode: 0644
    owner: "{{ user }}"

- copy:
    src: ./files/terminator.conf
    dest: "{{ home }}/.config/terminator/config"
    mode: 0644
    owner: "{{ user }}"

- copy:
    src: ./files/uniemoji.json
    dest: "{{ home }}/.config/uniemoji/custom.json"
    mode: 0644
    owner: "{{ user }}"

- copy:
    src: ./files/assh.yml
    dest: "{{ home}}/.ssh/assh.yml"
    mode: 0644
    owner: "{{ user }}"

- copy:
    src: ./files/gitignore_global
    dest: "{{ home }}/.config/.gitignore"
    mode: 0644
    owner: "{{ user }}"

- template:
    src: ./files/gitconfig.conf
    dest: "{{ home }}/.gitconfig"
    mode: 0644
    owner: "{{ user }}"
    group: users

- copy:
    src: ./files/rofi.conf
    dest: "{{ home }}/.config/rofi/config"
    mode: 0644
    owner: "{{ user }}"

- copy:
    src: ./files/touchpad.conf
    dest: /usr/share/X11/xorg.conf.d/30-touchpad.conf
    mode: 0644
    owner: "{{ user }}"

- copy:
    src: ./files/caret-preferences.md
    dest: "{{ home }}/.config/Caret/Preferences.md"
    mode: 0644
    owner: "{{ user }}"

- copy:
    src: ./files/alacritty.yml
    dest: "{{ home }}/.config/alacritty/alacritty.yml"
    mode: 0644
    owner: "{{ user }}"

# - name: Tilix config
#   shell: "dconf load /etc/gexperts/Tilix/"
#   args:
#     stdin: "{{ lookup('file', './files/tilix.conf') }}"
#   become: true
#   become_user: jake
