- name: Install DabApps packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - heroku-cli
    - mercurial
    - ngrok
    - python-aws-mfa

- name: Clone DabApps Dotfiles
  git:
    repo: git@github.com:dabapps/dotfiles
    dest: "{{ home }}/Projects/dotfiles"
    force: true
  become: true
  become_user: "{{ user }}"

- name: Install DabApps EditorConfig
  file:
    src: "{{ home }}/Projects/dotfiles/.editorconfig"
    dest: "{{ home }}/Projects/.editorconfig"
    mode: 0644
    owner: "{{ user }}"
    state: link
    force: true

- name: Enable strip mercurial extension
  ini_file:
    path: "{{ home }}/.hgrc"
    section: extensions
    option: strip
    value: ""
    mode: 0644

- name: Enable strip mercurial extension
  ini_file:
    path: "{{ home }}/.hgrc"
    section: ui
    option: ignore
    value: "{{ home }}/.config/.gitignore"
    mode: 0644

- name: Install Crab service
  template:
    src: ./files/crab.service
    dest: /etc/systemd/system/crab.service
    mode: 0644
    owner: root
    group: root

- name: Install Zoom
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - zoom
    - zoom-firejail
