- name: "DabApps Dotfiles"
  git:
    repo: git@github.com:dabapps/dotfiles
    dest: "{{ home }}/Projects/dotfiles"
    force: true
  become: true
  become_user: "{{ user }}"

- file:
    src: "{{ home }}/Projects/dotfiles/.editorconfig"
    dest: "[{ home }}/Projects/.editorconfig"
    mode: 0644
    owner: "{{ user }}"
    state: link
    force: true
