- name: "Install LaTex tooling"
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  loop:
    - 'biber'
    - 'pandoc-bin'
    - 'texlive-most'

- name: "Install dev packages"
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  loop:
    - 'arduino'
    - 'arduino-cli'
    - 'arduino-builder'
    - 'aws-cli'
    - 'docker'
    - 'docker-compose'
    - 'firefox-developer-edition'
    - 'hugo'
    - 'poetry'
    - 'postgresql'
    - 'postman-bin'
    - 'sublime-text'
    - 'tig'

- name: "Create global .gitignore"
  copy:
    src: './files/gitignore_global'
    dest: '{{ home }}/.config/.gitignore'
    mode: 0644
    owner: "{{ user }}"

- name: "Install git config"
  template:
    src: ./files/gitconfig.conf
    dest: "{{ home }}/.gitconfig"
    mode: 0644
    owner: "{{ user }}"
    group: users
