- name: Install LaTex tooling
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - biber
    - pandoc-bin
    - texlive-most

- name: Install dev packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - ansible-base
    - arduino
    - arduino-cli
    - arduino-builder
    - docker
    - docker-compose
    - firefox-developer-edition
    - github-cli
    - hugo
    - insomnia-bin
    - postgresql
    - sublime-text
    - tig

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: true
  become: true

- name: Create global .gitignore
  copy:
    src: ./files/gitignore_global
    dest: "{{ home }}/.config/.gitignore"
    mode: 0644
    owner: "{{ user }}"

- name: Install git config
  template:
    src: ./files/gitconfig.conf
    dest: "{{ home }}/.gitconfig"
    mode: 0644
    owner: "{{ user }}"
    group: users
