- name: Add nautilus file templates
  copy:
    src: ./files/Templates
    dest: "{{ home }}"
    mode: 0644
    owner: "{{ user }}"
    group: users
    directory_mode: 0755

- name: Install Gnome packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - baobab
    - cheese
    - eog
    - evince
    - file-roller
    - fractal
    - gnome-backgrounds
    - gnome-calculator
    - gnome-disk-utility
    - gnome-firmware
    - gnome-latex
    - gnome-settings-daemon
    - gnome-system-monitor
    - gnome-usage
    - nautilus

- name: Install GTK tools
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - gtk-engine-murrine
    - lxappearance
    - numix-gtk-theme-git
    - matcha-gtk-theme
    - numix-square-icon-theme
    - qt5-styleplugins

- name: Set GTK theme
  dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "\"Matcha-dark-aliz\""
  become: true
  become_user: "{{ user }}"

- name: Set GTK icon theme
  dconf:
    key: /org/gnome/desktop/interface/icon-theme
    value: "\"Numix-Square\""
  become: true
  become_user: "{{ user }}"

- name: Install GTK2 config
  copy:
    src: ./files/gtkrc-2.0
    dest: "{{ home }}/.gtkrc-2.0"
    mode: 0644
    owner: "{{ user }}"

- name: Create GTK3 config directory
  file:
    path: "{{ home }}/.config/gtk-3.0/"
    state: directory
    owner: "{{ user }}"
    mode: 0755


- name: Install GTK3 config
  copy:
    src: ./files/gtk3-settings.ini
    dest: "{{ home }}/.config/gtk-3.0/settings.ini"
    mode: 0644
    owner: "{{ user }}"

- name: Autostart gnome-settings services
  file:
    src: /etc/xdg/autostart/{{ item }}.desktop
    dest: "{{ home }}/.config/autostart/{{ item }}.desktop"
    mode: 0644
    owner: "{{ user }}"
    state: link
    force: true
  loop:
    - org.gnome.SettingsDaemon.XSettings
    - org.gnome.SettingsDaemon.DiskUtilityNotify
    - org.gnome.SettingsDaemon.Keyboard
    - gsettings-data-convert
