- name: Install i3 packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - arandr
    - flameshot
    - rofi
    - rofi-calc
    - rofimoji
    - xdotool

- name: Create rofi config directory
  file:
    path: "{{ home }}/.config/rofi/"
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: Create rofi config
  copy:
    src: ./files/rofi.rasi
    dest: "{{ home }}/.config/rofi/config.rasi"
    mode: 0644
    owner: "{{ user }}"

- name: Install pranklock
  get_url:
    url: https://raw.githubusercontent.com/RealOrangeOne/pranklock/master/pranklock
    dest: /usr/bin/pranklock
    mode: 0755
    force: true
