- template:
    src: ./files/i3status-rust.toml
    dest: "{{ home }}/.config/i3/status.toml"
    mode: 0644
    owner: "{{ user }}"
    group: users

- set_fact:
    i3_config_files:
      - {src: "i3.conf", dest: "{{ home }}/.config/i3/config"}
      - {src: "i3status.conf", dest: "{{ home }}/.config/i3status/config"}
      - {src: "compton.conf", dest: "{{ home }}/.config/compton.conf"}
      - {src: "dunst.conf", dest: "{{ home }}/.config/dunst/dunstrc"}

- name: "Create i3 config file directories"
  with_items: "{{ user_config_files }}"
  file:
    path: '{{ item.dest | dirname }}'
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: "Copy i3 config files"
  with_items: "{{ user_config_files }}"
  copy:
    src: './files/{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0644
    owner: "{{ user }}"
