- name: Install input packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - gpointing-device-settings
    - gromit-mpx
    - ibus
    - ibus-uniemoji
    - libinput
    - libinput-gestures
    - solaar
    - xorg-xev

- name: Install mouse config
  copy:
    src: ./files/touchpad.conf
    dest: /usr/share/X11/xorg.conf.d/30-touchpad.conf
    mode: 0644
    owner: "{{ user }}"

- name: Install keyboard config
  copy:
    src: ./files/keyboard.conf
    dest: /usr/share/X11/xorg.conf.d/00-keyboard.conf
    mode: 0644
    owner: "{{ user }}"

- name: Install libinput-gestures config
  copy:
    src: ./files/libinput-gestures.conf
    dest: /etc/libinput-gestures.conf
    mode: 0644
    owner: "{{ user }}"

- name: Create uniemoji config directory
  file:
    path: "{{ home }}/.config/uniemoji/"
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: Create uniemoji config
  copy:
    src: ./files/uniemoji.json
    dest: "{{ home }}/.config/uniemoji/custom.json"
    mode: 0644
    owner: "{{ user }}"

- name: Enable GB locale
  locale_gen:
    name: en_GB.UTF-8

- name: Enable US locale
  locale_gen:
    name: en_US.UTF-8

- name: Make the FN key work the correct way on Apple keyboards
  lineinfile:
    path: /etc/modprobe.d/hid_apple.conf
    line: options hid_apple fnmode=2
    create: true
    mode: 0644

- name: Create gromit-mpx config
  copy:
    src: ./files/gromit-mpx.cfg
    dest: "{{ home }}/.config/gromit-mpx.cfg"
    mode: 0644
    owner: "{{ user }}"
