- name: "Install intersect packages"
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  loop:
    - 'calibre'
    - 'deluge'
    - 'feedreader'
    - 'nextcloud-client'
    - "quassel-client"
    - 'turtl'


- name: Create dotfiles directory
  file:
    state: directory
    path: "{{ home }}/.dotfiles"
    owner: "{{ user }}"
    group: users
