- name: Install qownnotes
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - aspell
    - aspell-en
    - qownnotes

- name: Install intersect packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - calibre
    - deluge
    - nextcloud-client
    - quassel-client
    - terraform
    - terraform-lsp-bin


- name: Create dotfiles directory
  file:
    state: directory
    path: "{{ home }}/.dotfiles"
    owner: "{{ user }}"
    group: users
    mode: 0700
