- name: Install intersect packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - calibre
    - nextcloud-client
    - quassel-client
    - rsnapshot
    - terraform
    - terraform-lsp-bin

- name: Create dotfiles directory
  file:
    state: directory
    path: "{{ home }}/.dotfiles"
    owner: "{{ user }}"
    group: users
    mode: 0700
