- name: Install Javascript packages
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - nodejs
    - nvm
