- name: Create private directory
  file:
    state: directory
    recurse: true
    path: "{{ home }}/Private"
    owner: "{{ user }}"
    mode: 0700

- name: Create KeepassXC config directory
  file:
    state: directory
    recurse: true
    path: "{{ home }}/.config/keepassxc"
    owner: "{{ user }}"
    mode: 0700

- name: Set KeepassXC configuration
  ini_file:
    path: "{{ home }}/.config/keepassxc/keepassxc.ini"
    mode: 0700
    owner: "{{ user }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop_control:
    label: "{{ item.section }}.{{ item.option }}={{ item.value }}"
  loop:
    - {section: Browser, option: Enabled, value: "true"}
    - {section: Browser, option: AlwaysAllowAccess, value: "true"}
    - {section: Browser, option: AlwaysAllowUpdate, value: "true"}
    - {section: General, option: AutoSaveAfterEveryChange, value: "true"}
    - {section: General, option: LastOpenedDatabases, value: "{{ home }}/Private/Keepass/Password Safe.kdbx"}
    - {section: General, option: LastActiveDatabase, value: "{{ home }}/Private/Keepass/Password Safe.kdbx"}
    - {section: General, option: SingleInstance, value: "true"}
    - {section: generator, option: Length, value: 100}
    - {section: GUI, option: AdvancedSettings, value: "true"}
    - {section: GUI, option: ShowTrayIcon, value: "true"}
    - {section: GUI, option: MinimizeToTray, value: "true"}
    - {section: GUI, option: MinimizeOnStartup, value: "true"}
    - {section: GUI, option: MinimizeOnClose, value: "true"}
    - {section: Http, option: Enabled, value: "false"}
    - {section: security, option: lockdatabasescreenlock, value: "true"}
    - {section: security, option: clearclipboardtimeout, value: 60}
