- name: Install macOS packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - mbpfan-git
    - bcwc-pcie-git

- name: Enable mbpfan service
  systemd:
    name: mbpfan
    enabled: true
    state: started

- name: Disable power key
  lineinfile:
    path: /etc/systemd/logind.conf
    state: present
    regexp: ^HandlePowerKey=
    line: HandlePowerKey=ignore
