- name: Install media-related packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - alsa-firmware
    - cameractrls
    - handbrake
    - sof-firmware
    - spotify
