- name: Install Spotify
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - ffmpeg-compat-57
    - spotify

- name: Install media-related packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - alsa-firmware
    - bluez-firmware
    - bluez-utils-compat
    - blueman
    - handbrake
    - sof-firmware

- name: Install pulseaudio
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - alsa-utils
    - pavucontrol
    - pulseaudio
    - pulseaudio-bluetooth
