- name: Install networking tools
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - bind-tools
    - gnu-netcat
    - nmap

- name: Install NetworkManager and associated tools
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - networkmanager
    - network-manager-applet

- name: Enable NetworkManger
  systemd:
    name: NetworkManager
    enabled: true
    state: started
