- name: Install NTP
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - ntp

- name: Set timezone
  timezone:
    name: Europe/London

- name: Enable NTP service
  systemd:
    name: ntpd
    enabled: true
    state: started
