- set_fact:
    keys:
      - '1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A'  # Sublime Text
      - 'EF6E286DDA85EA2A4BA7DE684E2C6E8793298290'  # Tor Browser
      - '9D5F1C051D146843CDA4858BDE64825E7CBC0D51'  # ArchStrike

- name: "Get installed pacman keys"
  shell: "pacman-key --list-keys"
  register: pacman_keys

- name: "Add keys to pacman"
  shell: "pacman-key -r {{ item }}"
  when: "item not in pacman_keys.stdout"
  with_items: "{{ keys }}"

- name: "Sign keys in pacman"
  shell: "pacman-key --lsign-key {{ item }}"
  when: "item not in pacman_keys.stdout"
  with_items: "{{ keys }}"

- copy:
    src: ./files/pacman.conf
    dest: /etc/pacman.conf
    mode: 0644

- pacman:
    update_cache: true

- user:
    name: aur_builder
    group: wheel
    password_lock: true
    shell: /bin/false

- name: sudoers file
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'

- name: "Get installed packages"
  shell: "pacman -Qq"
  become: true
  become_user: aur_builder
  register: installed_packages

- name: "Install yay"
  aur:
    skip_installed: true
    name: yay
  become: true
  become_user: aur_builder

- name: "Install initial packages"
  aur:
    use: yay
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  with_items:
    - 'i3-gaps'
    - 'ttf-google-fonts-git'
    - 'i3lock-color-git'

- name: "Install packages"
  aur:
    use: yay
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: "item not in installed_packages.stdout_lines"
  with_items:
    - 'acpi'
    - 'advanced-ssh-config'
    - 'alacritty'
    - 'android-tools'
    - 'arandr'
    - 'archstrike-keyring'
    - 'arduino'
    - 'arduino-cli'
    - 'arduino-builder'
    - 'bat'
    - 'bcm20702a1-firmware'
    - 'betterlockscreen'
    - 'bleachbit'
    - 'bluez-firmware'
    - 'brave-bin'
    - 'brightnessctl'
    - 'calibre'
    - 'caprine'
    - 'catimg'
    - 'climate'
    - 'clamtk'
    - 'corebird'
    - 'compton'
    - 'deluge'
    - 'dex'
    - 'dmenu'
    - 'dunst'
    - 'enpass-bin'
    - 'etcher'
    - 'exa'
    - 'fasd'
    - 'fd'
    - 'feedreader'
    - 'feh'
    - 'filezilla'
    - 'firefox'
    - 'flameshot'
    - 'fonts-meta-extended-lt'
    - 'gimp'
    - 'ghostwriter'
    - 'glogg'
    - 'google-earth-pro'
    - 'gparted'
    - 'grub-customizer'
    - 'grub2-theme-archlinux'
    - 'gvim'
    - 'handbrake'
    - 'hexchat'
    - 'htop'
    - 'hugo'
    - 'ibus'
    - 'ibus-uniemoji'
    - 'inkscape'
    - 'intellij-idea-ultimate-edition'
    - 'intellij-idea-ultimate-edition-jre'
    - 'intellij-jdk'
    - 'jdk'
    - 'jshon'
    - 'kdenlive'
    - 'keybase-bin'
    - 'kodi'
    - 'libinput'
    - 'libinput-gestures'
    - 'lxappearance'
    - 'lxrandr'
    - 'lxqt-policykit'
    - 'ly-git'
    - 'minecraft'
    - 'mullvad-vpn'
    - 'networkmanager-wireguard-git'
    - 'nextcloud-client'
    - 'nnn'
    - 'nodejs'
    - 'numix-gtk-theme'
    - 'nvm'
    - 'obs-studio'
    - 'oh-my-zsh-git'
    - 'onlyoffice-bin'
    - 'otf-fira-code'
    - 'otf-font-awesome'
    - 'perl-file-mimeinfo'
    - 'pigz'
    - 'playerctl'
    - 'aur/polybar'
    - 'postgresql'
    - 'postman-bin'
    - 'powertop'
    - 'psensor'
    - 'pulseaudio-bluetooth-a2dp-gdm-fix'
    - 'pyenv'
    - 'python-pip'
    - 'python-virtualenv'
    - 'python2-pip'
    - 'python2-virtualenv'
    - 'qomui'
    - 'qt5-styleplugins'
    - 'redis'
    - 'redshift'
    - 'reptyr'
    - 'ripgrep'
    - 'rofi'
    - 'scrcpy'
    - 'screenfetch'
    - 'sl'
    - 'slack-desktop'
    - 'solaar'
    - 'spotify'
    - 'steam'
    - 'sublime-text'
    - 'sysstat'
    - 'tbg'
    - 'terminator'
    - 'thefuck'
    - 'thunderbird'
    - 'tig'
    - 'tmux'
    - 'tor-browser'
    - 'ttf-emojione'
    - 'ttf-fira-code'
    - 'ttf-font-awesome'
    - 'ttf-ms-fonts'
    - 'ttf-wps-fonts'
    - 'universal-ctags-git'
    - 'vim-pathogen'
    - 'visual-studio-code-bin'
    - 'virtualbox'
    - 'vivaldi'
    - 'vlc'
    - 'whatsie'
    - 'wireguard-dkms'
    - 'wireguard-tools'
    - 'wps-office'
    - 'wps-office-extension-english-uk-dictionary'
    - 'zola-bin'
    - 'zsh'
    - 'zsh-completions'
    - 'zsh-doc'
    - 'zsh-syntax-highlighting'

- service:
    name: "mullvad-daemon"
    enabled: true
