- user:
    name: aur_builder
    group: wheel

- name: sudoers file
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'

- name: "Install yay"
  aur:
    skip_installed: true
    name: yay
  become: true
  become_user: aur_builder

- name: "Install initial packages"
  aur:
    use: yay
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  with_items:
    - 'i3-gaps'
    - 'ttf-google-fonts-git'
    - 'i3lock-color-git'

- name: "Install packages"
  aur:
    use: yay
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  with_items:
    - 'acpi'
    - 'advanced-ssh-config'
    - 'alacritty-git'
    - 'android-tools'
    - 'archstrike-keyring'
    - 'arduino'
    - 'arduino-cli'
    - 'arduino-builder'
    - 'bat'
    - 'bcm20702a1-firmware'
    - 'betterlockscreen'
    - 'bleachbit'
    - 'bluez-firmware'
    - 'brave-bin'
    - 'brightnessctl'
    - 'calibre'
    - 'caprine'
    - 'catimg'
    - 'climate'
    - 'clamtk'
    - 'corebird'
    - 'compton'
    - 'deluge'
    - 'dex'
    - 'dmenu'
    - 'dunst'
    - 'etcher'
    - 'exa'
    - 'fasd'
    - 'fd'
    - 'feedreader'
    - 'feh'
    - 'filezilla'
    - 'firefox'
    - 'firefox-developer-edition'
    - 'fonts-meta-extended-lt'
    - 'gimp'
    - 'glogg'
    - 'google-earth-pro'
    - 'gparted'
    - 'grub-customizer'
    - 'grub2-theme-archlinux'
    - 'gvim'
    - 'handbrake'
    - 'hexchat'
    - 'htop'
    - 'i3status'
    - 'i3status-rust'
    - 'ibus'
    - 'ibus-uniemoji'
    - 'inkscape'
    - 'intellij-idea-ultimate-edition'
    - 'intellij-idea-ultimate-edition-jre'
    - 'intellij-jdk'
    - 'jdk'
    - 'jshon'
    - 'kdenlive'
    - 'keepassxc'
    - 'keybase-bin'
    - 'kodi'
    - 'libinput'
    - 'libinput-gestures'
    - 'lightdm'
    - 'lightdm-webkit2-greeter'
    - 'lxappearance'
    - 'lxpolkit-git'
    - 'lxrandr'
    - 'minecraft'
    - 'nextcloud-client'
    - 'nnn'
    - 'nodejs'
    - 'numix-gtk-theme'
    - 'nvm'
    - 'obs-studio'
    - 'oh-my-zsh-git'
    - 'onlyoffice-bin'
    - 'otf-fira-code'
    - 'otf-font-awesome'
    - 'perl-file-mimeinfo'
    - 'pigz'
    - 'playerctl'
    - 'postgresql'
    - 'postman-bin'
    - 'powertop'
    - 'psensor'
    - 'pulseaudio-bluetooth-a2dp-gdm-fix'
    - 'pyenv'
    - 'pyenv-virtualenv'
    - 'python-pip'
    - 'python-virtualenv'
    - 'python2-pip'
    - 'python2-virtualenv'
    - 'qt5-styleplugins'
    - 'redis'
    - 'redshift'
    - 'reptyr'
    - 'rofi'
    - 'scrcpy'
    - 'screenfetch'
    - 'sl'
    - 'slack-desktop'
    - 'solaar'
    - 'spotify'
    - 'steam'
    - 'sublime-text'
    - 'sysstat'
    - 'tbg'
    - 'terminator'
    - 'thefuck'
    - 'thunderbird'
    - 'tig'
    - 'tmux'
    - 'tor-browser-en'
    - 'ttf-emojione'
    - 'ttf-fira-code'
    - 'ttf-font-awesome'
    - 'ttf-ms-fonts'
    - 'ttf-wps-fonts'
    - 'universal-ctags-git'
    - 'visual-studio-code-bin'
    - 'virtualbox'
    - 'vivaldi'
    - 'vlc'
    - 'whatsie'
    - 'wps-office'
    - 'wps-office-extension-english-uk-dictionary'
    - 'yaourt'
    - 'zsh'
    - 'zsh-completions'
    - 'zsh-doc'
    - 'zsh-syntax-highlighting'

- user:
    name: aur_builder
    state: absent
