- name: Install pacman config
  template:
    src: ./files/pacman.conf
    dest: /etc/pacman.conf
    mode: 0644

- name: Create aur_builder user
  user:
    name: aur_builder
    group: wheel
    password_lock: true
    shell: /usr/bin/nologin
  changed_when: false

- name: Allow aur_builder user to run pacman as root
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: visudo -cf %s
    mode: 0644
  changed_when: false

- name: Install yay
  aur:
    name: yay-bin
  become: true
  become_user: aur_builder

- name: Install additional repo keyrings
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - archstrike-keyring

- name: Install ccache
  aur:
    name: ccache
  become: true
  become_user: aur_builder

- name: Install makepkg tools
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - pbzip2
    - zstd

- name: Install makepkg config
  template:
    src: ./files/makepkg.conf
    dest: /etc/makepkg.conf
    mode: 0644
