- name: Install power-saving stuff
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - acpi
    - ethtool
    - powertop
    - psensor
    - smartmontools
    - sysstat
    - xfce4-power-manager

- name: Create XFCE4 power manager config directory
  file:
    path: "{{ home }}/.config/xfce4/xfconf/xfce-perchannel-xml"
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: Install XFCE4 power manager config
  copy:
    src: ./files/xfce4-power-manager.xml
    dest: "{{ home }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    owner: "{{ user }}"
    mode: 0644
