- name: Install python packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - pyenv
    - python-pip
    - python-virtualenv
    - python2-pip
    - python2-virtualenv

- name: Create pyenv directory
  file:
    state: directory
    path: /opt/pyenv
    owner: "{{ user }}"
    group: users
