- name: Install python packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - pyenv
    - python-pip
    - python-virtualenv

- name: Create pyenv directory
  file:
    state: directory
    path: /opt/pyenv
    owner: "{{ user }}"
    group: users
    mode: 0644
