- name: Install security-related packages
  aur:
    skip_installed: true
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  when: item not in installed_packages.stdout_lines
  loop:
    - enpass-bin
    - keepassxc
    - qomui
    - wireguard-tools

- name: Create .ssh directory
  file:
    state: directory
    path: "{{ home }}/.ssh"
    owner: "{{ user }}"
    mode: 0700
    directory_mode: 0700

- name: Install assh config
  copy:
    src: ./files/assh.yml
    dest: "{{ home }}/.ssh/assh.yml"
    mode: 0644
    owner: "{{ user }}"
