- name: Install security-related packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - gnome-keyring
    - firejail
    - keepassxc
    - seahorse
    - wireguard-tools
    - yubikey-personalization-gui

- name: Create .ssh directory
  file:
    state: directory
    path: "{{ home }}/.ssh"
    owner: "{{ user }}"
    mode: 0700

- name: Install assh config
  copy:
    src: ./files/assh.yml
    dest: "{{ home }}/.ssh/assh.yml"
    mode: 0644
    owner: "{{ user }}"
