- copy:
    src: ./files/powertop.service
    dest: /etc/systemd/system/powertop.service
    mode: 0644
    owner: root
    directory_mode: true

- service:
    name: "powertop"
    enabled: true
    state: started
