- template:
    src: ./files/zshrc/.zshrc
    dest: "{{ home }}/.zshrc"
    mode: 0644
    owner: "{{ user }}"
    validate: "zsh -n %s"
    backup: true
    trim_blocks: false

- template:
    src: ./files/global-environment
    dest: /etc/environment
    mode: 0644
    owner: root
    group: root

- template:
    src: ./files/tmux.conf
    dest: "{{ home }}/.tmux.conf"
    mode: 0755
    owner: "{{ user }}"
    group: users

- git:
    repo: git@github.com:jimeh/tmux-themepack.git
    dest: "{{ home }}/.tmux/plugins/tmux-themepack"
    force: true
  become: true
  become_user: "{{ user }}"
