- template:
    src: ./files/zshrc/.zshrc
    dest: "{{ home }}/.zshrc"
    mode: 0644
    owner: "{{ user }}"
    validate: "zsh -n %s"
    backup: true
    trim_blocks: false

- copy:
    src: /usr/share/nvm/init-nvm.sh
    dest: "{{ home }}/.nvm/nvm.sh"
    mode: 0755
    owner: "{{ user }}"
    group: users

- copy:
    src: ./files/bin
    dest: "{{ home }}/.bin"
    mode: 0755
    owner: "{{ user }}"
    group: users
    directory_mode: true

- copy:
    src: ./files/global-environment
    dest: /etc/environment
    mode: 0644
    owner: root
    group: root

- copy:
    src: ./files/tmux.conf
    dest: "{{ home }}/.tmux.conf"
    mode: 0755
    owner: "{{ user }}"
    group: users
