- name: Install shell packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - alacritty
    - arch-install-scripts
    - atuin
    - bat
    - catimg
    - climate
    - cmatrix
    - direnv
    - eza
    - fd
    - fpp
    - htop
    - jshon
    - jq
    - man-db
    - nnn
    - oh-my-zsh-git
    - pazi
    - perl-file-mimeinfo
    - pipes.sh
    - playerctl
    - posix
    - progress
    - reptyr
    - ripgrep
    - scrcpy
    - screenfetch
    - speedtest-cli
    - sl
    - thefuck
    - usbutils
    - xclip
    - xsel
    - zsh
    - zsh-completions
    - zsh-doc
    - zsh-fast-syntax-highlighting

- name: Install ZSH config
  copy:
    src: ./files/zshrc
    dest: "{{ home }}/.zshrc"
    mode: 0644
    owner: "{{ user }}"
    validate: zsh -n %s
    backup: true

- name: Create alacritty config directory
  file:
    path: "{{ home }}/.config/alacritty/"
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: Create alacritty config
  copy:
    src: ./files/alacritty.yml
    dest: "{{ home }}/.config/alacritty/alacritty.yml"
    mode: 0644
    owner: "{{ user }}"

- name: Create direnv config directory
  file:
    path: "{{ home }}/.config/direnv/"
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: Create direnv config
  copy:
    src: ./files/direnv.toml
    dest: "{{ home }}/.config/direnv/direnv.toml"
    mode: 0644
    owner: "{{ user }}"

- name: Install custom scripts
  copy:
    src: ./files/bin
    dest: /usr/local
    mode: 0755
    directory_mode: 0755

- name: Set vconsole keyboard
  lineinfile:
    path: /etc/vconsole.conf
    state: present
    line: KEYMAP=uk
    create: true
    mode: 0644

- name: Create atuin config directory
  file:
    path: "{{ home }}/.config/atuin/"
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: Create atuin config
  copy:
    src: ./files/atuin.toml
    dest: "{{ home }}/.config/atuin/config.toml"
    mode: 0644
    owner: "{{ user }}"
