- user:
    name: "{{ user }}"
    home: "{{ home }}"
    comment: Jake Howard
    shell: '/usr/bin/zsh'
    uid: 1000
    system: true
    groups:
      - input
      - users
      - video
      - wheel

- file:
    state: directory
    path: '{{ home }}/Projects'
    owner: "{{ user }}"
