- name: Make me
  user:
    name: "{{ user }}"
    home: "{{ home }}"
    comment: Jake Howard
    shell: '/usr/bin/zsh'
    system: true
    groups:
      - input
      - users
      - video
      - wheel
      - tty
      - uucp

- name: Give user sudo access
  lineinfile:
    path: /etc/sudoers
    line: "{{ user }} ALL=(ALL) ALL"
