- name: Make me
  user:
    name: "{{ user }}"
    home: "{{ home }}"
    comment: Jake Howard
    shell: /usr/bin/zsh
    system: true
    groups:
      - audio
      - games
      - input
      - lp
      - power
      - scanner
      - storage
      - tty
      - users
      - uucp
      - video
      - wheel

- name: Give user sudo access
  lineinfile:
    path: /etc/sudoers.d/00_jake
    line: "{{ user }} ALL=(ALL) ALL"
    create: true
    validate: visudo -cf %s
    mode: 0640
