- copy:
    src: ./files/vimrc
    dest: "{{ home }}/.vimrc"
    mode: 0644
    owner: "{{ user }}"
    group: users

- copy:
    src: ./files/vimrc
    dest: /root/.vimrc
    mode: 0644
    owner: root
    group: users

- file:
    path: '{{ home }}/.vim/bundle'
    state: directory
    owner: "{{ user }}"
    mode: 0755

- name: Install vim packages
  git:
    repo: "{{ item }}"
    dest: "{{ home }}/.vim/bundle/{{ item.split('/')[-1] }}"
    force: true
  become: true
  become_user: "{{ user }}"
  with_items:
    - 'https://github.com/junegunn/goyo.vim'
    - 'https://github.com/itchyny/lightline.vim'
    - 'https://github.com/scrooloose/nerdtree'
    - 'https://github.com/vim-scripts/peaksea'
    - 'https://github.com/terryma/vim-multiple-cursors'
    - 'https://github.com/jremmen/vim-ripgrep'
    - 'https://github.com/amix/vim-zenroom2'
