- copy:
    src: ./files/vimrc
    dest: /home/jake/.vimrc
    mode: 0644
    owner: jake
    group: users

- copy:
    src: ./files/vimrc
    dest: /root/.vimrc
    mode: 0644
    owner: root
    group: users

- git:
    repo: https://github.com/amix/vimrc.git
    dest: /usr/share/amix_vimrc
    force: true
