- name: Install vim
  aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - gvim

- name: Install vimrc
  copy:
    src: ./files/vimrc
    dest: "{{ home }}/.vimrc"
    mode: 0644
    owner: "{{ user }}"
    group: users

- name: Install vimrc for root user
  copy:
    src: ./files/vimrc
    dest: /root/.vimrc
    mode: 0644
    owner: root
    group: users
