version: 2.0

jobs:
    build:
        docker:
            - image: circleci/ruby:latest
        working_directory: ~/dotfiles
        steps:
            - checkout
            - run: gem install puppet-lint
            - run: puppet-lint modules/ -c .puppet-lint.rc
            - run: puppet-lint manifests/ -c .puppet-lint.rc
