version: 2.0

jobs:
    build:
        docker:
            - image: circleci/python:latest
        working_directory: ~/dotfiles
        steps:
            - checkout
            - restore_cache:
                key: cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - run: pipenv install --dev --deploy
            - run: git clone https://github.com/kewlfft/ansible-aur.git ~/.ansible/plugins/modules/aur --depth=1
            - save_cache:
                key: cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                paths:
                    - "/home/circleci/.local/share/virtualenvs"
            - run: pipenv run lint
            - run: pipenv run check
