version: 2.0

jobs:
    build:
        docker:
            - image: circleci/python:latest
        working_directory: ~/dotfiles
        steps:
            - checkout
            - run: pipenv install
            - run: pipenv run test
            - run: pipenv run deploy -C
