version: 2.0

jobs:
    build:
        docker:
            - image: circleci/python:latest
        working_directory: ~/dotfiles
        steps:
            - checkout
            - run: ./scripts/setup.sh
            - run: git clone https://github.com/kewlfft/ansible-aur.git ~/.ansible/plugins/modules/aur --depth=1
            - run: ./scripts/lint.sh
