version: 2.0

jobs:
    build:
        docker:
            - image: antergos/archlinux-base-devel
            environment:
                PATH: ${HOME}/dotfiles/stubs/:${PATH}
        working_directory: ~/dotfiles
        steps:
            - checkout
            - run: git submodule update --init
            - run: pacman -Sy yaourt puppet --noconfirm
