version: 2.0

jobs:
    build:
        docker:
            - image: puppet/puppet-agent-ubuntu
        working_directory: ~/dotfiles
        steps:
            - checkout
            - run: git submodule update --init
            - run: puppet parser validate manifests/main.pp --modulepath=modules/ --verbose
