version: 2.0

jobs:
    build:
        docker:
            - image: antergos/archlinux-base-devel
        working_directory: ~/dotfiles
        steps:
            - checkout
            - run: git submodule update --init
            - run: cat .circleci/pacman.conf >> /etc/pacman.conf
            - run: pacman -Syu yaourt puppet patch --noconfirm
            - run: ./deploy.sh
