version: 2.0

jobs:
    build:
        docker:
            - image: fr3nd/puppet
        working_directory: ~/dotfiles
        steps:
            - run: apt install git -y
            - checkout
            - run: git submodule update --init
            - run: puppet parser validate manifests/main.pp --modulepath=modules/ --verbose
