version: 2.0

jobs:
    build:
        docker:
            - image: antergos/archlinux-base-devel
        working_directory: ~/dotfiles
        steps:
            - run: pacman -Syu
            - checkout
            - run: git submodule update --init
