set runtimepath+=~/.vim_runtime
set rtp+=/usr/share/vim/vimfiles/autoload/vundle.vim

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
  source ~/.vim_runtime/my_configs.vim
catch
endtry

cmap w!! w !sudo tee >/dev/null %
:set mouse=a

call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'rykka/clickable-things'

call vundle#end()            " required
filetype plugin indent on
