set runtimepath+=/usr/share/amix_vimrc

source /usr/share/amix_vimrc/vimrcs/basic.vim
source /usr/share/amix_vimrc/vimrcs/filetypes.vim
source /usr/share/amix_vimrc/vimrcs/plugins_config.vim
source /usr/share/amix_vimrc/vimrcs/extended.vim

cmap w!! w !sudo tee >/dev/null %
:set mouse=a

filetype plugin indent on
