theme = "plain"
icons = "awesome"

[[block]]
block = "xrandr"
interval = 5
icons = true

[[block]]
block = "music"
player = "spotify"
marquee = true
buttons = ["play", "next"]

[[block]]
block = "temperature"
interval = 5

[[block]]
block = "memory"
format_mem = "{Mup}%"
clickable = false
interval = 2

[[block]]
block = "cpu"
interval = 2

[[block]]
block = "sound"
interval = 1
step_width = 2

{% if ansible_fqdn == "TOO-Laptop" %}
[[block]]
block = "battery"
interval = 5
{% endif %}

[[block]]
block = "time"
interval = 1
format = "%Y-%m-%d %T"
