execute pathogen#infect()

let g:lightline = {'colorscheme': 'wombat'}

cmap w!! w !sudo tee >/dev/null %
:set mouse=a

syntax on
filetype plugin indent on

set laststatus=2

if !has('gui_running')
  set t_Co=256
endif

set background=dark
colorscheme peaksea
